version: "2"
services:
  ui:
    image: agenda_ui
    volumes:
     - ./client:/work/
     - /work/node_modules
    ports:
     - "3000:3000"
     - "9229:9229"
    links:
     - api
  api:
    image: agenda_api
    volumes:
     - ./server:/work/
     - /work/node_modules
     - /work/dist
    ports:
     - "3001:3001"
     - "9230:9229"
    links:
     - mongo
    environment:
     - API_URL=http://api:3001/contact
  mongo:
   image: mongo:4.0.2
   ports:
     - "27017:27017"
   volumes:
     - mongo_data:/data/db
     - ./data:/data/exchange

volumes:
  mongo_data:
