version: "2"
services:
  ui:
    image: agenda_ui
    links:
     - api
  api:
    image: agenda_api
    links:
     - mongo
  mongo:
   image: mongo:4.0.2
   volumes:
     - mongo_data:/data/db

volumes:
  mongo_data:
